"""Add performance indexes

Revision ID: ac3c7ce59da6
Revises: a7681d1258d6
Create Date: 2026-01-12 19:30:57.452183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac3c7ce59da6'
down_revision: Union[str, Sequence[str], None] = 'a7681d1258d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery_list_items', schema=None) as batch_op:
        batch_op.alter_column('retail_package',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('exact_amount',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipes_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_recipes_cuisine'), ['cuisine'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipes_cuisine'))
        batch_op.drop_index(batch_op.f('ix_recipes_created_at'))
        batch_op.drop_index(batch_op.f('ix_recipes_category'))

    with op.batch_alter_table('grocery_list_items', schema=None) as batch_op:
        batch_op.alter_column('exact_amount',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('retail_package',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
